//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataAdministrator))]
    public partial class Administrator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administrator()
        {
            this.Announcements = new HashSet<Announcement>();
        }
    
        public string ID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announcement> Announcements { get; set; }
    }
}
