//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataCity))]
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.Districts = new HashSet<District>();
        }
    
        public int ID { get; set; }
        public string CityName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District> Districts { get; set; }
    }
}
