//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataCoupon))]
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.PlayerCouponDetails = new HashSet<PlayerCouponDetail>();
        }
    
        public string ID { get; set; }
        public string ShopID { get; set; }
        public string Content { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int PointsRequired { get; set; }
        public Nullable<int> LimitedAmount { get; set; }
        public Nullable<int> RemainedAmount { get; set; }
        public Nullable<int> ExchangedAmount { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCouponDetail> PlayerCouponDetails { get; set; }
    }
}
