//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataDistrict))]
    public partial class District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public District()
        {
            this.Players = new HashSet<Player>();
            this.Shops = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int CityID { get; set; }
        public string DistrictName { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
