//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataShop))]
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Coupons = new HashSet<Coupon>();
            this.NormalOffers = new HashSet<NormalOffer>();
            this.TableGameInShopDetails = new HashSet<TableGameInShopDetail>();
            this.Teams = new HashSet<Team>();
        }
    
        public string ID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string ShopName { get; set; }
        public string OpeningHours { get; set; }
        public int DistrictID { get; set; }
        public string Address { get; set; }
        public bool IsMinConsumeRequired { get; set; }
        public bool IsFoodAcceptable { get; set; }
        public string AreaScale { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Line { get; set; }
        public string Website { get; set; }
        public bool IsVIP { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> AccumulatedHours { get; set; }
        public bool IsAccountEnabled { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NormalOffer> NormalOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableGameInShopDetail> TableGameInShopDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
