//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataTableGame))]
    public partial class TableGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableGame()
        {
            this.RelevantLinks = new HashSet<RelevantLink>();
            this.TableGameInShopDetails = new HashSet<TableGameInShopDetail>();
            this.TableGameVisitedStatistics = new HashSet<TableGameVisitedStatistic>();
            this.TableGameComments = new HashSet<TableGameComment>();
            this.GameCategoryTags = new HashSet<Tag>();
        }
    
        public string ID { get; set; }
        public string ChineseName { get; set; }
        public string EnglishName { get; set; }
        public bool IsExtended { get; set; }
        public short MinPlayer { get; set; }
        public short MaxPlayer { get; set; }
        public short AverageGamePeroid { get; set; }
        public string DetailGamePeroid { get; set; }
        public string Feature { get; set; }
        public string Rules { get; set; }
        public bool IsShown { get; set; }
        public string DifficultyTagID { get; set; }
        public string BrandTagID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelevantLink> RelevantLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableGameInShopDetail> TableGameInShopDetails { get; set; }
        public virtual Tag DifficultyTag { get; set; }
        public virtual Tag BrandTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableGameVisitedStatistic> TableGameVisitedStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableGameComment> TableGameComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> GameCategoryTags { get; set; }
    }
}
