//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Messages = new HashSet<Message>();
            this.OtherPlayers = new HashSet<Player>();
        }
    
        public string ID { get; set; }
        public string ShopID { get; set; }
        public string LeaderPlayerID { get; set; }
        public System.DateTime ParticipateEndDate { get; set; }
        public string Notes { get; set; }
        public System.DateTime PlayDate { get; set; }
        public System.TimeSpan PlayBeginTime { get; set; }
        public System.TimeSpan PlayEndTime { get; set; }
        public Nullable<int> EstimatedCost { get; set; }
        public string Preference { get; set; }
        public int MinPlayer { get; set; }
        public int MaxPlayer { get; set; }
        public bool IsCanceled { get; set; }
        public bool IsClosed { get; set; }
        public string Title { get; set; }
        public bool IsRequestSent { get; set; }
        public Nullable<bool> IsConfirmedByShop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Player LeaderPlayer { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> OtherPlayers { get; set; }
    }
}
