//------------------------------------------------------------------------------
// <auto-generated>
//     ?™å€‹ç?å¼ç¢¼?¯ç”±ç¯„æœ¬?¢ç???
//
//     å°é€™å€‹æ?æ¡ˆé€²è??‹å?è®Šæ›´?¯èƒ½å°è‡´?¨ç??‰ç”¨ç¨‹å??¢ç??ªé??Ÿç?è¡Œç‚º??
//     å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?å°‡æ?è¦†å¯«å°é€™å€‹æ?æ¡ˆç??‹å?è®Šæ›´??
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetadataTeam))]
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Messages = new HashSet<Message>();
            this.OtherPlayers = new HashSet<Player>();
        }
    
        public string ID { get; set; }
        public string ShopID { get; set; }
        public string LeaderPlayerID { get; set; }
        public string Title { get; set; }
        public System.DateTime ParticipateBeginDate { get; set; }
        public System.DateTime ParticipateEndDate { get; set; }
        public System.DateTime PlayBeginTime { get; set; }
        public System.DateTime PlayEndTime { get; set; }
        public string MinPlayers { get; set; }
        public string PlayPreference { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Player LeaderPlayer { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> OtherPlayers { get; set; }
    }
}
