//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TGISDBEntities : DbContext
    {
        public TGISDBEntities()
            : base("name=TGISDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerCouponDetail> PlayerCouponDetails { get; set; }
        public virtual DbSet<PlayerPointDetail> PlayerPointDetails { get; set; }
        public virtual DbSet<RelevantLink> RelevantLinks { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<TableGame> TableGames { get; set; }
        public virtual DbSet<TableGameComment> TableGameComments { get; set; }
        public virtual DbSet<TableGameInShopDetail> TableGameInShopDetails { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<NormalOffer> NormalOffers { get; set; }
        public virtual DbSet<TableGameVisitedStatistic> TableGameVisitedStatistics { get; set; }
    }
}
